from php:7.3-apache

RUN apt-get update && apt-get install -y apt-utils libpng-dev libjpeg-dev libpq-dev unzip git \
  && rm -rf /var/lib/apt/lists/* \
  && docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr \
  && docker-php-ext-install pdo_mysql gd mbstring opcache

WORKDIR /var/www